services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        USER_UID: 1000

    volumes:
      - type: bind
        source: ..
        target: /usr/src/app
        consistency: cached
